# Generated by Django 5.2.17 on 2026-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paid_course__isnull', False), ('paid_lesson__isnull', True)), models.Q(('paid_course__isnull', True), ('paid_lesson__isnull', False)), _connector='OR'), name='payment_exactly_one_item'),
        ),
    ]
